// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXPOYYpxqwK7w2TSgtJXWo2WvNmGQkERc',
    appId: '1:900859690726:web:82713ecafb7801a7f74527',
    messagingSenderId: '900859690726',
    projectId: 'sparkmate1',
    authDomain: 'sparkmate1.firebaseapp.com',
    storageBucket: 'sparkmate1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ1yollAOxhEuXNqbFhO0lqfb3yftlrRk',
    appId: '1:900859690726:android:3a6a3d10ac0f319cf74527',
    messagingSenderId: '900859690726',
    projectId: 'sparkmate1',
    storageBucket: 'sparkmate1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2IA24Djr7rPXYz_p7G4SGosR2uWjaN7w',
    appId: '1:900859690726:ios:62777f96934a0ae8f74527',
    messagingSenderId: '900859690726',
    projectId: 'sparkmate1',
    storageBucket: 'sparkmate1.firebasestorage.app',
    iosBundleId: 'com.example.sparkmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2IA24Djr7rPXYz_p7G4SGosR2uWjaN7w',
    appId: '1:900859690726:ios:62777f96934a0ae8f74527',
    messagingSenderId: '900859690726',
    projectId: 'sparkmate1',
    storageBucket: 'sparkmate1.firebasestorage.app',
    iosBundleId: 'com.example.sparkmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXPOYYpxqwK7w2TSgtJXWo2WvNmGQkERc',
    appId: '1:900859690726:web:e0c0d9ab521ba30ef74527',
    messagingSenderId: '900859690726',
    projectId: 'sparkmate1',
    authDomain: 'sparkmate1.firebaseapp.com',
    storageBucket: 'sparkmate1.firebasestorage.app',
  );

}